# Generated by Django 3.0.7 on 2020-10-23 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Entry',
            fields=[
                ('patient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_no', models.IntegerField(primary_key=True, serialize=False)),
                ('admission_type', models.CharField(choices=[('IN_PATIENT', 'IN_PATIENT'), ('OUT_PATIENT', 'OUT_PATIENT')], default='OUT_PATIENT', max_length=15)),
                ('billed_datetime', models.DateTimeField(blank=True, null=True)),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('billed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('UN_LOCKED', 'UN_LOCKED'), ('LOCKED', 'LOCKED')], default='UN_LOCKED', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_chart',
            fields=[
                ('doctor_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dept', models.CharField(blank=True, max_length=25)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('availability', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_chart',
            fields=[
                ('Service_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Service_Type', models.CharField(max_length=25)),
                ('charge', models.FloatField(default=0.0)),
                ('perc10_Total', models.FloatField(default=0.0)),
                ('perc15', models.FloatField(default=0.0)),
                ('perc15_Total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField(default=501501)),
                ('dob', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER')], default='MALE', max_length=15)),
                ('martial_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE')], default='SINGLE', max_length=15)),
                ('nationality', models.CharField(choices=[('INDIAN', 'INDIAN'), ('FOREIGNER', 'FOREIGNER')], default='INDIAN', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_reg', models.DateTimeField(default=datetime.datetime(2020, 10, 23, 20, 21, 51, 401042))),
                ('reg_validity', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 20, 21, 51, 401042))),
                ('OPID', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('CONSULTATION', 'CONSULTATION'), ('LAB_TESTS', 'LAB_TESTS'), ('OTHERS', 'OTHERS')], default='CONSULTATION', max_length=15)),
                ('service_name', models.CharField(max_length=150)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('service_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('visit_type', models.CharField(default='WALK_IN', max_length=20)),
                ('Ref_by', models.CharField(default='None', max_length=20)),
                ('status', models.CharField(choices=[('UN_LOCKED', 'UN_LOCKED'), ('LOCKED', 'LOCKED')], default='UN_LOCKED', max_length=15)),
                ('bill_entry_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_entry_ref', to='testapp1.Bill_Entry')),
            ],
        ),
        migrations.AddField(
            model_name='bill_entry',
            name='reg_entry_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_entry_ref', to='testapp1.Registration'),
        ),
    ]
