# Generated by Django 3.0.7 on 2020-10-26 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0005_auto_20201024_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_entry',
            name='card_issued_bank',
            field=models.CharField(default='empty', max_length=10),
        ),
        migrations.AddField(
            model_name='bill_entry',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('BOTH', 'BOTH')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='bill_entry',
            name='paid_by_card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill_entry',
            name='paid_by_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill_entry',
            name='return_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill_entry',
            name='tx_id_reference',
            field=models.CharField(default='empt', max_length=4),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 0, 45, 9, 164003)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 0, 45, 9, 164003)),
        ),
    ]
