# Generated by Django 3.0.7 on 2020-11-03 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0006_auto_20201027_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 26, 54, 299360)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 11, 26, 54, 299360)),
        ),
        migrations.CreateModel(
            name='Appointment_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('appt_type', models.CharField(choices=[('CONSULTATION', 'CONSULTATION'), ('LAB_TESTS', 'LAB_TESTS'), ('FOLLOW_UP', 'FOLLOW_UP')], default='CONSULTATION', max_length=15)),
                ('appt_purpose', models.CharField(blank=True, max_length=150, null=True)),
                ('appt_date', models.DateField(blank=True, null=True)),
                ('appt_time', models.TimeField(blank=True, null=True)),
                ('Ref_by', models.CharField(default='None', max_length=20)),
                ('status', models.CharField(choices=[('UN_LOCKED', 'UN_LOCKED'), ('LOCKED', 'LOCKED')], default='UN_LOCKED', max_length=15)),
                ('reg_entry_ref1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_entry_ref1', to='testapp1.Registration')),
            ],
        ),
    ]
