# Generated by Django 3.0.7 on 2020-11-03 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0007_auto_20201103_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_item',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment_item',
            name='OPID',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 13, 20, 40, 420964)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 13, 20, 40, 420964)),
        ),
    ]
