# Generated by Django 3.0.7 on 2020-11-12 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0012_auto_20201103_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_entry',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment_item',
            name='patient_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 30, 54, 702889)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 18, 30, 54, 702889)),
        ),
    ]
