# Generated by Django 3.0.7 on 2020-11-22 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0017_auto_20201122_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_item',
            name='_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 16, 6, 49, 825833)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 16, 6, 49, 825833)),
        ),
    ]
