# Generated by Django 3.0.7 on 2020-11-22 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0018_auto_20201122_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_item',
            old_name='_phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 16, 14, 44, 304596)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 16, 14, 44, 304596)),
        ),
    ]
