# Generated by Django 3.0.7 on 2020-11-22 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0021_auto_20201122_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 23, 43, 34, 757361)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 23, 43, 34, 757361)),
        ),
    ]
