# Generated by Django 3.0.7 on 2020-10-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctor_name', models.CharField(blank=True, max_length=80, null=True)),
                ('hospital_id', models.CharField(default=0, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('print_name', models.CharField(max_length=200)),
                ('companyname', models.CharField(max_length=200)),
                ('HSN_code', models.CharField(max_length=20)),
                ('tabsPerStrip', models.IntegerField(default=10)),
                ('NumStrips', models.IntegerField(default=1)),
                ('Mfd_by', models.CharField(blank=True, max_length=200, null=True)),
                ('MRP', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('BatchNo', models.CharField(blank=True, max_length=20, null=True)),
                ('Mfd_date', models.DateField(blank=True, null=True)),
                ('Exp_date', models.DateField(blank=True, null=True)),
                ('purchase_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('purchase_cost_per_unit', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('sell_cost_per_unit', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('Qty_in', models.IntegerField(blank=True, null=True)),
                ('Qty_available', models.IntegerField(blank=True, null=True)),
                ('Discount_per', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('disc_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('tax_percent', models.DecimalField(decimal_places=3, default=0.12, max_digits=9)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('low_stock_ind_per', models.DecimalField(decimal_places=2, default=0.3, max_digits=2)),
                ('low_stock_ind_status', models.CharField(blank=True, default='OFF', max_length=3, null=True)),
                ('status', models.CharField(choices=[('UN_APPROVED', 'UN_APPROVED'), ('APPROVED', 'APPROVED')], default='UN_APPROVED', max_length=11)),
                ('sch', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Returned_Sell_Entry',
            fields=[
                ('rbill_no', models.IntegerField(primary_key=True, serialize=False)),
                ('rbill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('rbill_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('rbill_grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('returned_sell_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='UNLOCKED', max_length=10)),
                ('rmode_of_payment', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], default='CASH', max_length=10)),
                ('rtx_id_reference', models.CharField(default='empt', max_length=4)),
                ('card_issued_bank', models.CharField(default='empty', max_length=10)),
                ('rpayment_by_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rpayment_by_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('section', models.CharField(max_length=6)),
                ('classx', models.CharField(max_length=3)),
                ('lname', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('pemail', models.EmailField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Address',
            fields=[
                ('companyname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Entry',
            fields=[
                ('customer_address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.Customer_Address')),
                ('bill_no', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('sell_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNLOCKED', 'UNLOCKED'), ('LOCKED', 'LOCKED')], default='UNLOCKED', max_length=10)),
                ('mode_of_payment', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('BOTH', 'BOTH')], default='CASH', max_length=10)),
                ('tx_id_reference', models.CharField(default='empt', max_length=4)),
                ('card_issued_bank', models.CharField(default='empty', max_length=10)),
                ('paid_by_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_by_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('return_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            bases=('testapp.customer_address',),
        ),
        migrations.CreateModel(
            name='Returned_Out_Item_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchNo', models.CharField(blank=True, max_length=20, null=True)),
                ('Qty_returned', models.IntegerField(blank=True, null=True)),
                ('rbill_item_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('rbill_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('item_entry_ref1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_entry_ref1', to='testapp.Item_Entry')),
                ('rbill_no_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbill_no_ref', to='testapp.Returned_Sell_Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Entry',
            fields=[
                ('purchase_type', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT')], default='CREDIT', max_length=20)),
                ('invoice_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UN_APPROVED', 'UN_APPROVED'), ('APPROVED', 'APPROVED')], default='UN_APPROVED', max_length=11)),
                ('supplier_ref1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ref1', to='testapp.Supplier_Address')),
            ],
        ),
        migrations.AddField(
            model_name='item_entry',
            name='purchase_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_ref', to='testapp.Purchase_Entry'),
        ),
        migrations.AddField(
            model_name='item_entry',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ref', to='testapp.Supplier_Address'),
        ),
        migrations.AddField(
            model_name='returned_sell_entry',
            name='sell_entry_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_entry_ref', to='testapp.Sell_Entry'),
        ),
        migrations.CreateModel(
            name='Out_Item_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchNo', models.CharField(blank=True, max_length=20, null=True)),
                ('Qty_sold', models.IntegerField(blank=True, null=True)),
                ('bill_item_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('bill_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('status', models.CharField(choices=[('UNLOCKED', 'UNLOCKED'), ('LOCKED', 'LOCKED')], default='UNLOCKED', max_length=10)),
                ('item_entry_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_entry_ref', to='testapp.Item_Entry')),
                ('bill_no_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_no_ref', to='testapp.Sell_Entry')),
            ],
        ),
    ]
