# Generated by Django 3.0.7 on 2020-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_student_pname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('EmpId', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('phone', models.IntegerField()),
                ('dept', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
