# Generated by Django 3.0.7 on 2020-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20201023_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='returned_out_item_entry',
            name='status',
            field=models.CharField(choices=[('UNLOCKED', 'UNLOCKED'), ('LOCKED', 'LOCKED')], default='UNLOCKED', max_length=10),
        ),
    ]
