# Generated by Django 3.0.7 on 2020-11-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_returned_out_item_entry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('print_name', models.CharField(max_length=200)),
                ('Mfd_by', models.CharField(blank=True, max_length=200, null=True)),
                ('HSN_code', models.CharField(max_length=20)),
                ('MRP', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('BatchNo', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_percent', models.DecimalField(decimal_places=3, default=0.12, max_digits=9)),
                ('sch', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
