# Generated by Django 3.0.7 on 2020-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_item_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_master',
            name='MRP',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='tax_percent',
            field=models.FloatField(default=0.12),
        ),
    ]
