# Generated by Django 3.0.7 on 2020-11-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20201120_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_entry',
            name='sch',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
