# Generated by Django 3.0.7 on 2020-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20201122_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_entry',
            name='sch',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
