# Generated by Django 3.0.7 on 2020-11-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20201124_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out_item_entry',
            name='sell_disc_per',
        ),
    ]
