# Generated by Django 3.0.7 on 2020-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_remove_out_item_entry_sell_disc_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_item_entry',
            name='CGST_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='out_item_entry',
            name='CGST_tax_per',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='out_item_entry',
            name='IGST_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='out_item_entry',
            name='IGST_tax_per',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='out_item_entry',
            name='SGST_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='out_item_entry',
            name='SGST_tax_per',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
