# Generated by Django 3.0.7 on 2020-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20201124_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_entry',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
