# Generated by Django 3.0.7 on 2020-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20201125_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_item_entry',
            name='CGST_tax_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='out_item_entry',
            name='SGST_tax_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='out_item_entry',
            name='bill_item_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='out_item_entry',
            name='bill_tax_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
