# Generated by Django 3.0.7 on 2020-11-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20201125_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='FYear_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
