# Generated by Django 3.0.7 on 2020-11-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_fyear_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyear_table',
            name='Year',
            field=models.CharField(max_length=15),
        ),
    ]
