# Generated by Django 3.0.7 on 2020-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20201126_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_entry',
            name='CGST_tax_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchase_entry',
            name='SGST_tax_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
